### ISSUE TITLE
Install fails due to incorrect filename

### ISSUE THREAD

**Issue by ReagentX** [Abeilles8/NightSky#2]
The file in the repo is misnamed:

https://github.com/Abeilles8/NightSky/blob/2facd42ce7cf1dceb57f94c7cb7420997d8a5772/theme/night-sky-color-theme1.json

The package.json declares it without the 1:

https://github.com/Abeilles8/NightSky/blob/2facd42ce7cf1dceb57f94c7cb7420997d8a5772/package.json#L32

**Comment by Abeilles8** [comment]
Hello.
Thank you for your comment.
I am sorry that you could not install the software due to my mistake.
We have released a new version [v1.05] with a corrected file name, so please download it again from the install button.
If you have any further questions, please let me know.

https://github.com/Abeilles8/NightSky/blob/8f92561e15fd94184c874e92f58ad988a63d9d4a/theme/night-sky-color-theme.json
